server:
  port: ${PORT:8761}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
  serviceUrl:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

    
