# YAML template.
server:
 port: 8888
spring:
 profiles:
  active: native
 cloud:
  config:
   server:
    git:
     uri: https://github.com/habuma/cloud-native-spring-config-server
     #username: Git username
     #password: Git password