server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          
          uri: https://github.com/alejopalacioduque/microServices
          search-paths:
            - config